//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeGame.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int PlayerID { get; set; }
        public Nullable<int> ItemSlot1 { get; set; }
        public Nullable<int> ItemSlot2 { get; set; }
        public Nullable<int> ItemSlot3 { get; set; }
        public Nullable<int> ItemSlot4 { get; set; }
        public Nullable<int> ItemSlot5 { get; set; }
        public Nullable<int> ItemSlot6 { get; set; }
        public Nullable<int> ItemSlot7 { get; set; }
        public Nullable<int> ItemSlot8 { get; set; }
        public Nullable<int> ItemSlot9 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
    }
}
